### ISSUE TITLE
Getting image fetch failed when this concourse ci resource is used together with Concourse CI 7.8+

### ISSUE THREAD

**Issue by larssb** [w32blaster/telegram-notification-resource#6]
I bumped Concourse CI to v7.11.2 and now I'm getting:

```text
image fetching failed
```

When the `telegram-notification-resource` step in my Concourse CI pipeline ran. It worked fine under Concourse CI v7.7.

I see that this resource is no longer listed under [Concourse CI resource types](https://resource-types.concourse-ci.org/)

- Is it dead/no longer working?

Thank you very much @w32blaster

**Comment by larssb** [comment]
Hmm fixed it myself. Switched to the [registry-image resource](https://github.com/concourse/registry-image-resource) instead. That made it work. In the description of that resource it also said that the `docker-image` resource is intended to be deprecated ( whenever that happens ).

Have a great one.

**Comment by w32blaster** [comment]
Thank you! Apologies, I haven't touched this repo for a while 😅 I'm glad you sorted out it
